version: '3.4'

services:
  tutorialdb:
    container_name: tutorialdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  tutorial.api:
    container_name: tutorial.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://tutorialdb:27017"
    depends_on:
      - tutorialdb
    ports:
      - "8000:80"


  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
    depends_on:
      - cartdb
    ports:
      - "8001:80"

