version: '3.4'

services:
  tutorialdb:
    image: mongo

  cartdb:
    image: redis:alpine
  
  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  tutorial.api:
    image: ${DOCKER_REGISTRY-}tutorialapi
    build:
      context: .
      dockerfile: Services\Tutorial\Tutorial.API\Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
