version: '3.4'

services:
  tutorialdb:
    container_name: tutorialdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  tutorial.api:
    container_name: tutorial.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://tutorialdb:27017"
    depends_on:
      - tutorialdb
    ports:
      - "8000:80"